### ISSUE TITLE
How to Add multiple sensors

### ISSUE THREAD

**Issue by electromitter** [stelford/home-assistant_inkbird#2]
Can u give me an example to add 2 sensors to the configuration.yaml

**Comment by stelford** [comment]
sure.. sorry, I haven't been around these parts much lately. It's jst the same as adding in any multiple sensor to home assisstant really..

```
sensor:
  - platform: inkbird
    mac: '90:e2:02:9b:45:3a'
    name: 'Cians Room'
    scan_interval: 120
    monitored_conditions:
      - temperature
      - humidity
  - platform: inkbird
    mac: '90:e2:02:9b:4b:64'
    name: 'Kats Room'
    scan_interval: 120
    monitored_conditions:
      - temperature
      - humidity
  - platform: inkbird
    mac: '90:e2:02:99:cd:ae'
    name: 'Our Room'
    scan_interval: 120
    monitored_conditions:
      - temperature
      - humidity
  - platform: inkbird
    mac: '90:e2:02:99:be:3b'
    name: 'Outside'
    scan_interval: 120
    monitored_conditions:
      - temperature
      - humidity
```
